[project]
name = "eta-kappa-notes"
version = "0.1.0"
dependencies = [
    "matplotlib",
    "numpy",
    "mpl-tools",
    "pyyaml>=6.0.3",
    "jsonschema>=4.25.1",
    "argh>=0.31.3",
]

[tool.setuptools]
py-modules = []
